using System.Collections.Generic;
using System.Linq;

namespace Pokemon
{
    public static partial class RedBlue
    {
        public readonly static Dictionary<int, char> HexToASCII = new Dictionary<string, char>()
        {
            { "A0", 'a' },
            { "A1", 'b' },
            { "A2", 'c' },
            { "A3", 'd' },
            { "A4", 'e' },
            { "A5", 'f' },
            { "A6", 'g' },
            { "A7", 'h' },
            { "A8", 'i' },
            { "A9", 'j' },
            { "AA", 'k' },
            { "AB", 'l' },
            { "AC", 'm' },
            { "AD", 'n' },
            { "AE", 'o' },
            { "AF", 'p' },
            { "B0", 'q' },
            { "B1", 'r' },
            { "B2", 's' },
            { "B3", 't' },
            { "B4", 'u' },
            { "B5", 'v' },
            { "B6", 'w' },
            { "B7", 'x' },
            { "B8", 'y' },
            { "B9", 'z' },
            { "80", 'A' },
            { "81", 'B' },
            { "82", 'C' },
            { "83", 'D' },
            { "84", 'E' },
            { "85", 'F' },
            { "86", 'G' },
            { "87", 'H' },
            { "88", 'I' },
            { "89", 'J' },
            { "8A", 'K' },
            { "8B", 'L' },
            { "8C", 'M' },
            { "8D", 'N' },
            { "8E", 'O' },
            { "8F", 'P' },
            { "90", 'Q' },
            { "91", 'R' },
            { "92", 'S' },
            { "93", 'T' },
            { "94", 'U' },
            { "95", 'V' },
            { "96", 'W' },
            { "97", 'X' },
            { "98", 'Y' },
            { "99", 'Z' },
            { "7e", '~' },
            { "EA", '`' },
            { "E7", '!' },
            { "9A", '(' },
            { "9B", ')' },
            { "E3", '-' },
            { "F4", ',' },
            { "F2", '.' },
            { "F3", '/' },
            { "9C", ':' },
            { "9D", ';' },
            { "E6", '?' },
            { "9E", '[' },
            { "9F", ']' }
        }.ToDictionary(item => int.Parse(item.Key,  System.Globalization.NumberStyles.HexNumber), item => item.Value);
    }
}